### PR TITLE
Added Mac compatibility

### PR DESCRIPTION
**Pull request by jkrielaars**
On a Apple system, the ARP table is returned in a different format from the Windows output. 
This pull-request makes the library compatible with Apple systems. 

**is()**
Since static/dynamic info is not available in the Apple response, the ```is('static', <addr>)``` and ```is('dynamic', <addr>)``` calls will throw an error with a relevant message on Apple systems. 

**tests** 
I have updated the tests to fake the ARP response on both Apple and WIndows systems

### CODE REVIEW

**Comment by jkrielaars** [comment]
Below is the arp output on CentOS. Looks like my PR adds compatibility for that as well...
```
[root@videorecorder ~]# arp -a
? (10.74.25.20) at 8c:dc:d4:31:7d:ff [ether] on eno1
gateway (10.74.25.1) at 00:04:96:9b:8a:92 [ether] on eno1
? (10.74.25.52) at 9c:b6:d0:be:8b:ad [ether] on eno1
? (10.74.25.254) at 00:6c:bc:ef:8e:1f [ether] on eno1
? (10.74.25.250) at a8:60:b6:1c:a2:11 [ether] on eno1
```

**Comment by justintaddei** [comment]
Thank you! I never realized the output was different on Unix systems.

**Comment by jkrielaars** [comment]
Np.

Glad I finally took the effort to make an attribution to open source software. 

Your package will be running in operating rooms (in hospitals) all over the Netherlands from next year.

Cheers!

**Comment by justintaddei** [comment]
I just published your changes as v1.2.0.

**Comment by justintaddei** [comment]
Make that v1.2.1 😂

I broke the type definitions...

**Comment by jkrielaars** [comment]
Lolz

**Pull request merged**
